export const THEME_DATA = {
  "code-vibes": {
    name: "Code vibes",
    images: [
      "./assets/images/themes/code-vibes/angular.svg",
      "./assets/images/themes/code-vibes/bootstrap.svg",
      "./assets/images/themes/code-vibes/css.svg",
      "./assets/images/themes/code-vibes/django.svg",
      "./assets/images/themes/code-vibes/firebase.svg",
      "./assets/images/themes/code-vibes/git.svg",
      "./assets/images/themes/code-vibes/github.svg",
      "./assets/images/themes/code-vibes/html.svg",
      "./assets/images/themes/code-vibes/js.svg",
      "./assets/images/themes/code-vibes/node-js.svg",
      "./assets/images/themes/code-vibes/python.svg",
      "./assets/images/themes/code-vibes/react.svg",
      "./assets/images/themes/code-vibes/sass.svg",
      "./assets/images/themes/code-vibes/sql.svg",
      "./assets/images/themes/code-vibes/terminal.svg",
      "./assets/images/themes/code-vibes/ts.svg",
      "./assets/images/themes/code-vibes/vsc.svg",
      "./assets/images/themes/code-vibes/vue.svg",
    ],
    front: "./assets/images/themes/code-vibes/front.svg",
  },
  gaming: {
    name: "Gaming",
    images: [
      "./assets/images/themes/gaming/1up.svg",
      "./assets/images/themes/gaming/banana.svg",
      "./assets/images/themes/gaming/card.svg",
      "./assets/images/themes/gaming/circle.svg",
      "./assets/images/themes/gaming/coin.svg",
      "./assets/images/themes/gaming/controller.svg",
      "./assets/images/themes/gaming/dice.svg",
      "./assets/images/themes/gaming/gameboy.svg",
      "./assets/images/themes/gaming/levelup.svg",
      "./assets/images/themes/gaming/maze.svg",
      "./assets/images/themes/gaming/minecraft.svg",
      "./assets/images/themes/gaming/pacman.svg",
      "./assets/images/themes/gaming/pacman2.svg",
      "./assets/images/themes/gaming/play.svg",
      "./assets/images/themes/gaming/puzzle.svg",
      "./assets/images/themes/gaming/snake.svg",
      "./assets/images/themes/gaming/square.svg",
      "./assets/images/themes/gaming/triangle.svg",
    ],
    front: "./assets/images/themes/gaming/front.svg",
  },
};
